ci disabled

diff --git a/.github/workflows/databuild.yaml b/.github/workflows/databuild.yaml
--- a/.github/workflows/databuild.yaml
+++ b/.github/workflows/databuild.yaml
@@ -1,33 +1,33 @@
-# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
-# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
-on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
-    
-name: databuild
-
-jobs:
-  render:
-    name: databuild
-    runs-on: macOS-latest
-    env:
-      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-      GH_KEY: ${{ secrets.GH_KEY }}
-      GH_SECRET: ${{ secrets.GH_SECRET }}
-    steps:
-      - uses: actions/checkout@v2
-      - uses: r-lib/actions/setup-r@v1
-      - name: Copy data
-        run: Rscript -e 'source("R/dat_copy.R")'
-      - name: Commit results
-        run: |
-          git config --local user.email "actions@github.com"
-          git config --local user.name "GitHub Actions"
-          git add -A
-          git commit -m 'Re-build data' || echo "No changes to commit"
-          git push origin || echo "No changes to commit"
-        
+# # For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
+# # https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
+# on:
+#   push:
+#     branches:
+#       - main
+#   pull_request:
+#     branches:
+#       - main
+#     
+# name: databuild
+# 
+# jobs:
+#   render:
+#     name: databuild
+#     runs-on: macOS-latest
+#     env:
+#       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+#       GH_KEY: ${{ secrets.GH_KEY }}
+#       GH_SECRET: ${{ secrets.GH_SECRET }}
+#     steps:
+#       - uses: actions/checkout@v2
+#       - uses: r-lib/actions/setup-r@v1
+#       - name: Copy data
+#         run: Rscript -e 'source("R/dat_copy.R")'
+#       - name: Commit results
+#         run: |
+#           git config --local user.email "actions@github.com"
+#           git config --local user.name "GitHub Actions"
+#           git add -A
+#           git commit -m 'Re-build data' || echo "No changes to commit"
+#           git push origin || echo "No changes to commit"
+#         
